/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface":          "var(--c-inverse-on-surface)",
        "on-surface":                  "var(--c-on-surface)",
        "primary-fixed-dim":           "var(--c-primary-fixed-dim)",
        "on-tertiary":                 "var(--c-on-tertiary)",
        "tertiary-fixed-dim":          "var(--c-tertiary-fixed-dim)",
        "primary":                     "var(--c-primary)",
        "surface-container":           "var(--c-surface-container)",
        "on-secondary":                "var(--c-on-secondary)",
        "surface-tint":                "var(--c-surface-tint)",
        "on-error":                    "var(--c-on-error)",
        "surface-variant":             "var(--c-surface-variant)",
        "secondary-fixed-dim":         "var(--c-secondary-fixed-dim)",
        "surface-container-lowest":    "var(--c-surface-container-lowest)",
        "outline-variant":             "var(--c-outline-variant)",
        "outline":                     "var(--c-outline)",
        "surface":                     "var(--c-surface)",
        "background":                  "var(--c-surface)",
        "on-secondary-fixed":          "var(--c-on-secondary-fixed)",
        "secondary":                   "var(--c-secondary)",
        "tertiary-fixed":              "var(--c-tertiary-fixed)",
        "primary-fixed":               "var(--c-primary-fixed)",
        "tertiary":                    "var(--c-tertiary)",
        "on-primary-fixed-variant":    "var(--c-on-primary-fixed-variant)",
        "on-tertiary-container":       "var(--c-on-tertiary-container)",
        "on-secondary-fixed-variant":  "var(--c-on-secondary-fixed-variant)",
        "inverse-primary":             "var(--c-inverse-primary)",
        "tertiary-container":          "var(--c-tertiary-container)",
        "surface-container-low":       "var(--c-surface-container-low)",
        "on-primary":                  "var(--c-on-primary)",
        "surface-container-highest":   "var(--c-surface-container-highest)",
        "secondary-fixed":             "var(--c-secondary-fixed)",
        "on-tertiary-fixed":           "var(--c-on-tertiary-fixed)",
        "on-primary-container":        "var(--c-on-primary-container)",
        "error-container":             "var(--c-error-container)",
        "surface-dim":                 "var(--c-surface-dim)",
        "on-background":               "var(--c-on-surface)",
        "on-secondary-container":      "var(--c-on-secondary-container)",
        "primary-container":           "var(--c-primary-container)",
        "surface-bright":              "var(--c-surface-bright)",
        "inverse-surface":             "var(--c-inverse-surface)",
        "on-tertiary-fixed-variant":   "var(--c-on-tertiary-fixed-variant)",
        "surface-container-high":      "var(--c-surface-container-high)",
        "on-primary-fixed":            "var(--c-on-primary-fixed)",
        "on-error-container":          "var(--c-on-error-container)",
        "error":                       "var(--c-error)",
        "on-surface-variant":          "var(--c-on-surface-variant)",
        "secondary-container":         "var(--c-secondary-container)",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body":     ["Manrope"],
        "label":    ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
